name: OAuth workflow

on:
  push:
    branches:
      - be-release

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH로 EC2에 접속하기
      uses: appleboy/ssh-action@v1.0.3
      env:
          APPLICATION_PROPERTIES: ${{ secrets.OAUTH }}
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        envs: APPLICATION_PROPERTIES
        script_stop: true
        script: |
            cd /home/ubuntu/issue5 # 여기 경로는 자신의 EC2에 맞는 경로로 재작성하기
            echo "$APPLICATION_PROPERTIES" > src/main/resources/application-github.properties


